let bikesArr = [
    {
        name:"Royal Enfield 350",
        imgUrl : "./assets/imgs/royalEnfield.jpg",
        minBooking: "Min. Booking",
        minHour: "5 hr min",
        minBookRate: "Rs.450",
        hourlyRate: "Hourly Rate",
        hourlyRateHour:"After 5 hrs",
        extraRate: "Rs.29/hr",
        offer: "Online Special",
        discount: "10%",
        discountType: "First Rite",
        btn : "Book now"     
    },
    {
        name:"Bajaj Avenger",
        imgUrl : "./assets/imgs/avenger.jpg",
        minBooking: "Min. Booking",
        minHour: "5 hr min",
        minBookRate: "Rs.330",
        hourlyRate: "Hourly Rate",
        hourlyRateHour:"After 5 hrs",
        extraRate: "Rs.20/hr",
        offer: "Online Special",
        discount: "10%",
        discountType: "First Rite",
        btn : "Book now"     
    },
    {
        name:"Bajaj Pulsar",
        imgUrl : "./assets/imgs/pulsur.jpg",
        minBooking: "Min. Booking",
        minHour: "5 hr min",
        minBookRate: "Rs.270",
        hourlyRate: "Hourly Rate",
        hourlyRateHour:"After 5 hrs",
        extraRate: "Rs.16/hr",
        offer: "Online Special",
        discount: "10%",
        discountType: "First Rite",
        btn : "Book now"     
    },
    {
        name:"Honda Shine",
        imgUrl : "./assets/imgs/hondaShine.jpg",
        minBooking: "Min. Booking",
        minHour: "5 hr min",
        minBookRate: "Rs.230",
        hourlyRate: "Hourly Rate",
        hourlyRateHour:"After 5 hrs",
        extraRate: "Rs.13/hr",
        offer: "Online Special",
        discount: "10%",
        discountType: "First Rite",
        btn : "Book now"     
    },
    {
        name:"Hero CD Deluxe",
        imgUrl : "./assets/imgs/hondaCd.jpg",
        minBooking: "Min. Booking",
        minHour: "5 hr min",
        minBookRate: "Rs.210",
        hourlyRate: "Hourly Rate",
        hourlyRateHour:"After 5 hrs",
        extraRate: "Rs.13/hr",
        offer: "Online Special",
        discount: "10%",
        discountType: "First Rite",
        btn : "Book now"     
    },
    {
        name:"TVS Sports",
        imgUrl : "./assets/imgs/tvs.jpg",
        minBooking: "Min. Booking",
        minHour: "5 hr min",
        minBookRate: "Rs.200",
        hourlyRate: "Hourly Rate",
        hourlyRateHour:"After 5 hrs",
        extraRate: "Rs.13/hr",
        offer: "Online Special",
        discount: "10%",
        discountType: "First Rite",
        btn : "Book now"     
    },
    {
        name:"TVS Jupiter",
        imgUrl : "./assets/imgs/jupeter.jpg",
        minBooking: "Min. Booking",
        minHour: "5 hr min",
        minBookRate: "Rs.200",
        hourlyRate: "Hourly Rate",
        hourlyRateHour:"After 5 hrs",
        extraRate: "Rs.16/hr",
        offer: "Online Special",
        discount: "10%",
        discountType: "First Rite",
        btn : "Book now"     
    },
    {
        name:"Yamaha Fascino",
        imgUrl : "./assets/imgs/yamahafaskino.jpg",
        minBooking: "Min. Booking",
        minHour: "5 hr min",
        minBookRate: "Rs.200",
        hourlyRate: "Hourly Rate",
        hourlyRateHour:"After 5 hrs",
        extraRate: "Rs.16/hr",
        offer: "Online Special",
        discount: "10%",
        discountType: "First Rite",
        btn : "Book now"     
    },
    {
        name:"Activa 5g Limited Edition",
        imgUrl : "./assets/imgs/activa.jpg",
        minBooking: "Min. Booking",
        minHour: "5 hr min",
        minBookRate: "Rs.200",
        hourlyRate: "Hourly Rate",
        hourlyRateHour:"After 5 hrs",
        extraRate: "Rs.16/hr",
        offer: "Online Special",
        discount: "10%",
        discountType: "First Rite",
        btn : "Book now"     
    },

]